climate_learn_command:
  description: 'Learn an IR command, press "Call Service", point the remote at the IR device, and the learned command will be shown as a notification in Overview.'
  fields:
    host:
      description: "Name or host of the entity to learn command from."
      example: "climate.xiaomi_miio_airconditioningcompanion"
    slot:
      description: "Define the slot used to save the IR command. Defaults to slot ID 30."
      example: "30"
    timeout:
      description: "Define the timeout in seconds, before which the command must be learned."
      example: "30"

climate_send_command:
  description: 'Send captured infrared command or device configuration.'
  fields:
    host:
      description: "Name or host of the acpartner entity."
      example: "climate.xiaomi_miio_airconditioningcompanion"
    command:
      description: "Custom configured infrared command."
    packet:
      description: "Infrared command. Must start with FE or 01."
